import type { IconType } from "react-icons";
import {
  FaCode,
  FaCogs,
  FaDatabase,
  FaLayerGroup,
  FaLinkedinIn,
  FaNetworkWired,
  FaPhoneAlt,
  FaPlug,
  FaProjectDiagram,
  FaUsersCog,
} from "react-icons/fa";
import {
  SiAngular,
  SiApachecassandra,
  SiBitbucket,
  SiC,
  SiCss,
  SiDevexpress,
  SiDocker,
  SiDrizzle,
  SiExpress,
  SiGit,
  SiGithub,
  SiGmail,
  SiHtml5,
  SiJavascript,
  SiMui,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrimeng,
  SiPrisma,
  SiReactivex,
  SiReact,
  SiRedis,
  SiSharp,
  SiSocketdotio,
  SiSwagger,
  SiTypescript,
} from "react-icons/si";

const ICON_MAP: Record<string, IconType> = {
  FaCode,
  FaCogs,
  FaDatabase,
  FaLayerGroup,
  FaLinkedinIn,
  FaNetworkWired,
  FaPhoneAlt,
  FaPlug,
  FaProjectDiagram,
  FaUsersCog,
  SiAngular,
  SiApachecassandra,
  SiBitbucket,
  SiC,
  SiCss,
  SiDevexpress,
  SiDocker,
  SiDrizzle,
  SiExpress,
  SiGit,
  SiGithub,
  SiGmail,
  SiHtml5,
  SiJavascript,
  SiMui,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPrimeng,
  SiPrisma,
  SiReactivex,
  SiReact,
  SiRedis,
  SiSharp,
  SiSocketdotio,
  SiSwagger,
  SiTypescript,
};

export const ICON_KEYS = Object.keys(ICON_MAP).sort();

export function getIcon(iconKey?: string | null): IconType {
  if (!iconKey) return FaCode;
  return ICON_MAP[iconKey] ?? FaCode;
}
