import type { IconType } from "react-icons";
import {
  FaCode,
  FaCogs,
  FaDatabase,
  FaDiscord,
  FaFacebook,
  FaGlobe,
  FaInstagram,
  FaJava,
  FaLayerGroup,
  FaLink,
  FaLinkedinIn,
  FaNetworkWired,
  FaPhoneAlt,
  FaPlug,
  FaProjectDiagram,
  FaTelegram,
  FaTwitter,
  FaUsersCog,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import {
  SiAngular,
  SiApachecassandra,
  SiBitbucket,
  SiC,
  SiCodeforces,
  SiCplusplus,
  SiCss,
  SiDevexpress,
  SiDocker,
  SiDrizzle,
  SiExpress,
  SiGit,
  SiGithub,
  SiGmail,
  SiGo,
  SiHackerrank,
  SiHtml5,
  SiJavascript,
  SiKotlin,
  SiLeetcode,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrimeng,
  SiPrisma,
  SiPython,
  SiReactivex,
  SiReact,
  SiRedis,
  SiRuby,
  SiRust,
  SiSharp,
  SiSocketdotio,
  SiSwagger,
  SiSwift,
  SiTailwindcss,
  SiTypescript,
  SiVuedotjs,
  SiWhatsapp,
} from "react-icons/si";

const ICON_MAP: Record<string, IconType> = {
  FaCode,
  FaCogs,
  FaDatabase,
  FaDiscord,
  FaFacebook,
  FaGlobe,
  FaInstagram,
  FaJava,
  FaLayerGroup,
  FaLink,
  FaLinkedinIn,
  FaNetworkWired,
  FaPhoneAlt,
  FaPlug,
  FaProjectDiagram,
  FaTelegram,
  FaTwitter,
  FaUsersCog,
  FaWhatsapp,
  FaXTwitter,
  FaYoutube,
  SiAngular,
  SiApachecassandra,
  SiBitbucket,
  SiC,
  SiCodeforces,
  SiCplusplus,
  SiCss,
  SiDevexpress,
  SiDocker,
  SiDrizzle,
  SiExpress,
  SiGit,
  SiGithub,
  SiGmail,
  SiGo,
  SiHackerrank,
  SiHtml5,
  SiJavascript,
  SiKotlin,
  SiLeetcode,
  SiMongodb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPostman,
  SiPrimeng,
  SiPrisma,
  SiPython,
  SiReactivex,
  SiReact,
  SiRedis,
  SiRuby,
  SiRust,
  SiSharp,
  SiSocketdotio,
  SiSwagger,
  SiSwift,
  SiTailwindcss,
  SiTypescript,
  SiVuedotjs,
  SiWhatsapp,
};

export const ICON_KEYS = Object.keys(ICON_MAP).sort();

export function getIcon(iconKey?: string | null): IconType {
  if (!iconKey) return FaCode;
  // FaWhatsapp has extra SVG padding and looks smaller — prefer SiWhatsapp.
  if (iconKey === "FaWhatsapp") return SiWhatsapp;
  return ICON_MAP[iconKey] ?? FaCode;
}
